# Generated by Django 5.1.4 on 2025-06-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_record_habitrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustomhabits',
            name='completion_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
