# Generated by Django 5.1.4 on 2025-06-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('working', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('working_hours', models.IntegerField()),
            ],
        ),
    ]
